language: node_js
node_js:
  - v7
deploy:
  provider: npm
  email: antitim@yandex.ru
  api_key:
    secure: BKT6MMiDBWJCgZwpVXwf036c1tRxvbapUp8zEWVPxmCl1lTg0LEOuFw8//ZVwEdDI1WnGfotWrGaW2/60LaXthvyEc7M9P0AxavT3j5TtJsn6KrAlnG23s8ctOVTTpyNm9/9UEnEWdc1ZKWBlyH7it3T6LM+foA/MKLfJiEwjtG9Le0ddZrBChE3zE0L/MjriZ26h4g9TTAEb0O20FcnYUOP/TMVhwPYji5KH8X+6WrvHtlnimhgo4S7fYmoql32k8w6sllBGt5S1xF6F+DknKf1JYHibtstMR6xhHYD/z/DNCIJ2qKK90cRMueX9jXzMzqYisjHh//6wVSBtyc6ML7RQcAK7qhuMSU1uNVZr+e4cukaFQLMatlezHkPvcJh58U41jjyTrdf106PnYdXNvADHuF1kbUJaeLveg0HzZHXrDXRpasFsWs9SHIS1anu5yO1hxtDBZR0XfMXyeF7ky+FjxpiSBa/FM1n1OFaRR3/pVZibMaCv++guRsVx9lYm6bnAJGmNP6M6YQmSd0f5UBy2a0aUrh0/z2MIPbW8W8ixoTCnvbtUcZxvhtt6rDkH+MheQrSyJ727onGEdi8vzHZ79dp4pj6xWpX0CRRZPvv8QkSdKOKkmrq9ViMlEQxXU/e8eyYbuvayKsKrxHDwPeUtZRpVFOmmGA4v2ITnnM=

